name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaiquegazola
          config_output: gist
          config_gist: e0beea62232204bc0c22791a8ec63a62
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 2
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
